server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  profiles:
    active: local
  main:
   banner-mode: off
   jpa:
     hibernate:
     ddl-auto: create-drop
   my.prop: 'test'
task.allowMultipleTasksFromTemplate: false